### ISSUE TITLE
请问这个还能正常工作吗？

### ISSUE THREAD

**Issue by miRemid** [imlonghao/bilibili-live-recorder#7]
按照bilibili.go里面的方法，在接受弹幕消息那里，我解析不出弹幕消息，输出是空值
![](https://ftp.bmp.ovh/imgs/2019/10/7ebfdfd906d938fe.png)
![](https://ftp.bmp.ovh/imgs/2019/10/b9a27c25f279b1b9.png)

**Comment by imlonghao** [comment]
我看了看我的日志系统，现在还是能采集到数据的。

您这就给了我一小块代码也没法看的说...

**Comment by miRemid** [comment]
package main

import (
	"log"
	"bytes"
	"encoding/json"
	"encoding/binary"

	"github.com/miRemid/danmugo"	
	"github.com/miRemid/danmugo/model"		
)

func parse(message []byte) {
	// 头部信息
	h := message[:16]	
	var head model.RHeader
	buf := bytes.NewReader(h)
	binary.Read(buf, binary.BigEndian, &head)
	body := message[16:head.Length]
	log.Printf("opcode=%d\n", head.Type)

	switch head.Type {
	// 心跳响应
	case danmugo.WsHeartbeatReply:
		var rqz model.Population
		binary.Read(bytes.NewReader(body), binary.BigEndian, &rqz)
		log.Printf("wsHeartbeatReply:%v\n", rqz)
		break
	// 弹幕或广播
	case danmugo.WsMessage:
		var cmd model.CMD
		_ = json.Unmarshal(body, &cmd)
		log.Printf("CMD=%v\n", cmd)
		switch cmd.Cmd{
		case "DANMU_MSG":
			var danmaku model.Danmaku
			json.Unmarshal(body, &danmaku)
			log.Printf("%d - %s: %s\n", cmd.Info[2][1], danmaku.Info[1])
		}
	}
	next := message[head.Length:]
	if binary.Size(next) != 0 {
		parse(next)
	}
}

func main() {
	client := danmugo.NewClient(0)
	client.Login(5279)
	client.OnMessage(parse)
	client.Listen(30)
}
-------------------------------------
go run main.go 
2019/10/11 12:39:31 try to connect...
2019/10/11 12:39:31 connect successful
2019/10/11 12:39:31 RoomID=5279's token=AyGuoFj0PvSo7p9ACUAN3WBFHeg1G-Kfc426HlU_BzUZyHqnzgaj9i84RxeEjXaQNoic0a9mP1huYFBHcqju-Rh9YBJlwZ3p2ZSOclvXT-7DqQ==
2019/10/11 12:39:31 start Listening roomid=5279
2019/10/11 12:39:31 心跳包发送间隔为30s
2019/10/11 12:39:31 opcode=8
2019/10/11 12:39:31 opcode=5
2019/10/11 12:39:31 CMD={[] }
2019/10/11 12:39:33 opcode=5
2019/10/11 12:39:33 CMD={[] }
2019/10/11 12:39:34 opcode=5
2019/10/11 12:39:34 CMD={[] }
2019/10/11 12:39:36 opcode=5
2019/10/11 12:39:36 CMD={[] }
2019/10/11 12:39:36 opcode=3
2019/10/11 12:39:36 wsHeartbeatReply:{194762}

**Comment by miRemid** [comment]
```golang
package main


import (
	"log"
	"bytes"
	"encoding/json"
	"encoding/binary"

	"github.com/miRemid/danmugo"	
	"github.com/miRemid/danmugo/model"		
)

func parse(message []byte) {
	// 头部信息
	h := message[:16]	
	var head model.RHeader
	buf := bytes.NewReader(h)
	binary.Read(buf, binary.BigEndian, &head)
	body := message[16:head.Length]
	log.Printf("opcode=%d\n", head.Type)

	switch head.Type {
	// 心跳响应
	case danmugo.WsHeartbeatReply:
		var rqz model.Population
		binary.Read(bytes.NewReader(body), binary.BigEndian, &rqz)
		log.Printf("wsHeartbeatReply:%v\n", rqz)
		break
	// 弹幕或广播
	case danmugo.WsMessage:
		var cmd model.CMD
		_ = json.Unmarshal(body, &cmd)
		log.Printf("CMD=%v\n", cmd)
		switch cmd.Cmd{
		case "DANMU_MSG":
			var danmaku model.Danmaku
			json.Unmarshal(body, &danmaku)
			log.Printf("%d - %s: %s\n", cmd.Info[2][1], danmaku.Info[1])
		}
	}
	next := message[head.Length:]
	if binary.Size(next) != 0 {
		parse(next)
	}
}

func main() {
	client := danmugo.NewClient(0)
	client.Login(5279)
	client.OnMessage(parse)
	client.Listen(30)
}
```
```cmd
go run main.go 
2019/10/11 12:39:31 try to connect...
2019/10/11 12:39:31 connect successful
2019/10/11 12:39:31 RoomID=5279's token=AyGuoFj0PvSo7p9ACUAN3WBFHeg1G-Kfc426HlU_BzUZyHqnzgaj9i84RxeEjXaQNoic0a9mP1huYFBHcqju-Rh9YBJlwZ3p2ZSOclvXT-7DqQ==
2019/10/11 12:39:31 start Listening roomid=5279
2019/10/11 12:39:31 心跳包发送间隔为30s
2019/10/11 12:39:31 opcode=8
2019/10/11 12:39:31 opcode=5
2019/10/11 12:39:31 CMD={[] }
2019/10/11 12:39:33 opcode=5
2019/10/11 12:39:33 CMD={[] }
2019/10/11 12:39:34 opcode=5
2019/10/11 12:39:34 CMD={[] }
2019/10/11 12:39:36 opcode=5
2019/10/11 12:39:36 CMD={[] }
2019/10/11 12:39:36 opcode=3
2019/10/11 12:39:36 wsHeartbeatReply:{194762}
```

**Comment by imlonghao** [comment]
我不清楚 `ClientVer: 1.8.5` 下的弹幕消息是什么数据结构...

根据版本的不同，数据结构多多少少会有点不同。

(就例如我这不需要 token 你那需要 token)
